- name: Copy installer to ProgramData
  win_get_url:
    url: "http://{{ http_host }}/roles/mongodb/files/mongodb.msi"
    dest: "C:\\ProgramData\\mongodb.msi"

- name: Install MSI
  win_package:
    path: 'C:\\ProgramData\\mongodb.msi'
    arguments: '/quiet ADDLOCAL="ServerService"'
    state: present

- name: Delete MSI
  win_file:
    path: 'C:\\ProgramData\\mongodb.msi'
    ensure: absent
