- name: Update the package cache
    apt: 
      update_cache: yes

# Install Apache
- name: Install Apache
    apt: 
      name: apache2
      state: latest

- name: Add index.html
    copy:
      src: index.html
      dest: /var/www/html/index.html
      mode: '664'

- name: Enable Apache
    service: 
      name: apache2
      state: enabled
      enabled: yes

# Start Apache and ensure it is enabled to start automatically on reboot
- name: Start Apache
    service: 
      name: apache2
      state: started
      enabled: yes