- name: Common Linux Additions
  hosts: linux
  become: yes
  roles:
    - users

- name: Common Windows Additions
  hosts: windows
  become: no
  gather_facts: no
  roles:
    - winuser

- name: Common pfsense Additions
  hosts: pfsense
  become: no
  roles:
    - users

- name: morbius
  hosts: morbius
  become: no
  gather_facts: no
  roles:
    - AD
    - DNS

- name: jumanji
  hosts: jumanji
  become: yes
  roles:
    - apache

- name: zombieland
  hosts: zombieland
  become: no
  gather_facts: no
  roles:
    - mysql
    - mongodb

# - name: spiderman
#   hosts: spiderman
#   become: yes
#   roles:
#     - ssh

# - name: angrybirds
#   hosts: angrybirds
#   become: no
#   roles:
#     - ssh

- name: emoji
  hosts: emoji
  become: no
  roles:
    - rsync

- name: cinderella
  hosts: cinderella
  become: no
  gather_facts: no
  roles:
    - iis

- name: billyjoel
  hosts: billyjoel
  become: yes
  roles:
    - minecraft

- name: ghostbusters
  hosts: ghostbusters
  become: no
  gather_facts: no
  roles:
    - smb

- name: venom
  hosts: venom
  become: yes
  roles:
    - smtp
    - imap

# I have no clue if this works
- name: Add Windows Machines to AD
  hosts: winclients
  become: no
  gather_facts: no
  tasks:
    - name: Add to Domain
      ansible.windows.win_domain_membership:
        dns_domain_name: "{{ domain }}"
        domain_admin_user: "mlynton@{{ domain }}"
        domain_admin_password: changeme1!
        state: domain
      register: domain_state

    - name: Reboot to apply domain
      win_shell: "powershell Restart-Computer -Force"
      when: domain_state.reboot_required
