- name: Common Linux Additions
  hosts: linux
  become: yes
  roles:
    - users

- name: Common Windows Additions
  hosts: windows
  become: yes
  roles:
    - users

- name: Common pfsense Additions
  hosts: pfsense
  become: no
  roles:
    - users

- name: morbius
  hosts: morbius
  become: yes
  roles:
    - AD
    - DNS

- name: jumanji
  hosts: jumanji
  become: yes
  roles:
    - apache

- name: zombieland
  hosts: zombieland
  become: yes
  roles:
    - mysql
    - mongodb

# - name: spiderman
#   hosts: spiderman
#   become: yes
#   roles:
#     - ssh

# - name: angrybirds
#   hosts: angrybirds
#   become: no
#   roles:
#     - ssh

- name: emoji
  hosts: emoji
  become: no
  roles:
    - rsync

- name: cinderella
  hosts: cinderella
  become: yes
  roles:
    - iis

- name: billyjoel
  hosts: billyjoel
  become: yes
  roles:
    - minecraft

- name: ghostbusters
  hosts: ghostbusters
  become: yes
  roles:
    - smb

- name: venom
  hosts: venom
  become: yes
  roles:
    - smtp
    - imap

# I have no clue if this works
- name: Add Windows Machines to AD
  hosts: winclients
  become: yes
  tasks:
    - ansible.windows.win_domain_membership:
        dns_domain_name: {{ domain }}
        domain_admin_user: mlynton@{{ domain }}
        domain_admin_password: changeme1!
        state: domain
      register: domain_state

  - ansible.windows.win_reboot:
    when: domain_state.reboot_required

# I have no clue if this works
- name: Add Windows Machines to AD | Team 2
  hosts: sony2
  become: yes
  tasks:
    - ansible.windows.win_domain_membership:
        dns_domain_name: sony2.local
        domain_admin_user: mlynton@SONY2
        domain_admin_password: changeme1!
        state: domain
      register: domain_state

  - ansible.windows.win_reboot:
    when: domain_state.reboot_required