- name: Update the package cache
  apt:
    update_cache: yes

# Install aptitude
- name: Install aptitude
  apt:
    name: aptitude
    state: latest
    update_cache: true

# Install packages
- name: Install packages
  apt:
    pkg:
      - apt-transport-https
      - ca-certificates
      - curl
      - software-properties-common
      - python3-pip
      - virtualenv
      - python3-setuptools
      - lsb-release
      - gnupg
    state: latest
    update_cache: true

# Add signing key
- name: Add signing key
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present

# Add repository key
- name: Add repository key
  apt_repository:
    repo: deb https://download.docker.com/linux/ubuntu focal stable
    state: present

# Install Docker
- name: Install Docker
  apt:
    name: docker-ce
    state: latest
    update_cache: true

- name: Create Minecraft container
  community.docker.docker_container:
    image: itzg/minecraft-server:latest
    name: minecraft
    state: started
    auto_remove: false
    ports:
      - "25565:25565"
    env:
      EULA: "TRUE"