- name: Add AD Role # Set up IIS web server
  ansible.windows.win_feature: 
    name: "AD-Domain-Services"
    state: present
    include_sub_features: yes
    include_management_tools: yes

- name: Create new domain in a new forest on the target host
  ansible.windows.win_domain:
    dns_domain_name: "{{ domain }}"
    safe_mode_password: changeme1!
  register: ad

- name: reboot server
  win_reboot:
    pre_reboot_delay: 5
  when: ad.changed

- name: Create Blue Team User | Windows
  win_user:
    name: mlynton
    password: changeme1!
    groups:
      - Domain Users
      - Domain Admins
      - Enterprise Admins
      - Schema Admins
      - Administrators
    state: present
  when: ad.changed


- name: Create Grey Team User | Windows
  win_user:
    name: greyteam
    password: Greyteamiscool1!
    groups:
      - Domain Users
      - Domain Admins
      - Enterprise Admins
      - Schema Admins
      - Administrators
    state: present
  when: ad.changed
