- name: Add AD Role # Set up IIS web server
  ansible.windows.win_feature: 
    name: "AD-Domain-Services"
    state: present
    include_sub_features: yes
    include_management_tools: yes

- name: Create new domain in a new forest on the target host
  ansible.windows.win_domain:
    dns_domain_name: {{ domain }}
    safe_mode_password: changeme1!

- name: reboot server
    win_reboot:
      pre_reboot_delay: 15
    when: ad.changed
