- name: Copy installer to ProgramData
  win_get_url:
    url: "http://{{ http_host }}/roles/mysql/files/mysql.msi"
    dest: "C:\\ProgramData\\mysql.msi"

      #- name: Install MSI
      #win_package:
      #path: 'C:\\ProgramData\\mysql.msi'
      #arguments: '/quiet'
      #state: present

      #- name: Delete MSI
      #win_file:
      #path: 'C:\\ProgramData\\mysql.msi'
      #ensure: absent
