- name: Create Blue Team User | Windows
  win_user:
    name: mlynton
    password: changeme1!
    groups:
      #- Domain Admins
      #- Enterprise Admins
      #- Schema Admins
      - Administrators
    state: present
